create schema if not exists shop;

drop table if exists shop.product;

create table shop.product (
identifier INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1 INCREMENT BY 1) PRIMARY KEY,
name varchar(30),
price integer
);